### ISSUE TITLE
Add classes for testing purposes

### ISSUE THREAD

**Issue by acidin** [AndriyShepitsen/realty-advisers-north3#3]
For testing purposes we need classes. For start, add class for element - button "ALL HOMES FOR SALE (RENT)" on city page.

**Comment by acidin** [comment]
Also we need class for zip numbers, so we can click with selenium on them on the city page. I think, you may not add <code>, just class name.

**Comment by acidin** [comment]
And also, if possible, class for cities buttons on page /homes-for-sale
So we can click 'em.

**Comment by SvitlanaShepitsena** [comment]
Now we use CountButton component for "ALL HOMES FOR SALE (RENT)" button and for Zips - Property types. It has a <code> tag with a class for displaying numbers of listings.
The only issue in some cases React wraps value additionally in <span>

![buttonall](https://cloud.githubusercontent.com/assets/5209402/14824690/742cbde4-0b9c-11e6-9959-5cc46f18e4fd.jpg)
![zip](https://cloud.githubusercontent.com/assets/5209402/14824689/742946be-0b9c-11e6-8f28-937fc8776f31.jpg)

**Comment by SvitlanaShepitsena** [comment]
I have added <code> tag because of React additional spans, so we have finally bunch of spans :) , but if it does not work well, I can easily substitute with a <span> or any another

**Comment by acidin** [comment]
Svitlana, we need another class for zip numbers (60067 and etc).
And one more class for cities on the page /homes-for-sale/, for each city (Chicago, Aurora and etc).
So we can click them with Selenium and make automatic test possible.

**Comment by SvitlanaShepitsena** [comment]
Sure, cities on the page /homes-for-sale/apartments for rent
Please tell me if it work with you:
![cities](https://cloud.githubusercontent.com/assets/5209402/14828295/f6253baa-0bab-11e6-9af7-a4f9495dce48.jpg)

**Comment by SvitlanaShepitsena** [comment]
class for zip numbers (60067 and etc)

![citypage](https://cloud.githubusercontent.com/assets/5209402/14829120/878e8f58-0baf-11e6-82df-addbc29cadbd.jpg)

**Comment by SvitlanaShepitsena** [comment]
City Zip-Type page
![cityzip](https://cloud.githubusercontent.com/assets/5209402/14829148/a8bf5608-0baf-11e6-9d4b-80d123e7b22f.jpg)

**Comment by acidin** [comment]
Yes, we use this additional classes as well.
But we need two more classes for full automation.

**Comment by AndriyShepitsen** [comment]
Call us please

**Comment by SvitlanaShepitsena** [comment]
![citybox](https://cloud.githubusercontent.com/assets/5209402/14830593/0f359be8-0bb7-11e6-8f20-217506829549.jpg)
![zipnamebox](https://cloud.githubusercontent.com/assets/5209402/14830596/149e8806-0bb7-11e6-8c28-4d4b4e1742c6.jpg)
