### ISSUE TITLE
Refactoring of  Item types

### ISSUE THREAD

**Issue by AndriyShepitsen** [AndriyShepitsen/realty-advisers-north3#5]
Simplify and clean all app Entities in graphql/type folder.

Make sure that ... destructuring does not have errors and written in the most short and clear way :-)

**Comment by acidin** [comment]
I don't see how I can simplify and clean all app Entities in graphql/type folder ?

**Comment by AndriyShepitsen** [comment]
Well, I am sure that it's not the most effective code :-), I went over CityType - I removed Houses_Count_Rent and remove some comments and that's probably it.
