### ISSUE TITLE
Check that total number of houses on sale-city page is equal to the sum of zips split  

### ISSUE THREAD

**Issue by AndriyShepitsen** [AndriyShepitsen/realty-advisers-north3#7]

**Comment by acidin** [comment]
We have done it in some way with Selenium + Java, but also I propose to check total sum for every zip and split by types. I wrote comment for Svitlana to add another class name.

**Comment by AndriyShepitsen** [comment]
Great, though if you can teach Evgen Javascript. I started with Java but would prefer to add script to Java :+1: . But you decide

**Comment by acidin** [comment]
I propose start with main page, make cycle for every city, inside city check its total sum and splitted sum (by zips) and also nested cycle for every zip - check its sum and splitted sum (by types).
I think we can write it if Svitlana will add two more classes, I've explained task in different issue what we need.

**Comment by acidin** [comment]
https://github.com/SilverKain/RemaxTest/blob/master/TestChicago.java

Code has some simplifications for faster testing but it works!

For local setup you must change:
System.setProperty("webdriver.firefox.bin", "D:\\NewProgram\\Mozilla\\firefox.exe"); // your path
System.setProperty("webdriver.ie.driver", "C:\\selenium-2.51.0\\IEDriverServer.exe"); //your path
Instead String appUrl = "http://www.remax1stclass.com/homes-for-sale"; 
I propose String appUrl = "http://localhost:4444/homes-for-sale"; 
If you change for localhost, you can remove delays - Thread.sleep(1000);
Instead for (int k = 29; k < 33; k++) {
change to 
for (int k = 0; k < ElementCity.size(); k++) {
We were testing only small towns with moderate data.

**Comment by acidin** [comment]
New version of tests available:
https://github.com/SilverKain/qaz/blob/master/TestChicago.java
https://github.com/SilverKain/qaz/blob/master/TestChicago2.java

Difference: 
https://github.com/SilverKain/qaz/blob/master/TestChicago.java tests only first level of site.
Rest tests were commented.
So, you can dramatically decrease time of testing, and in a few minutes receive information.
By the way test show difference between all listings in Sale and splitted sum of all cities.
9952 vs 9951
Rent has identical results.
